### ISSUE TITLE
Digital inputs beta3.0

### ISSUE THREAD

**Issue by thomasinaz41213** [Lucifer06/RemoteGPIO#12]
The external digital inputs default is "unknown" when the module is installed and enabled. The default should be "disabled" to more coincide with the default Venus os behavior of the built in digital inputs.

**Comment by Lucifer06** [comment]
This is related to a bug in Venus OS, I believe Kevin have open the case: it correctly show up as "Generic I/O in the main page.
Meanwhile because I have now fixed the possibility to configure each input (broke the limit of 9) in the Digital Input Setting page, I will not anymore preset it as a function.
It will be implemented in beta 3.0.16

**Comment by Lucifer06** [comment]
fixed
